version: '3.2'
services:
    module-a:
      image: module-a:latest
      build:
        context: module-a
        dockerfile: ./Dockerfile
      container_name: module-a
      ports:
        - "8080:8080"

    module-b:
      image: module-b:latest
      build:
        context: module-b
        dockerfile: ./Dockerfile
      container_name: module-b
      ports:
        - "8083:8083"

    pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      container_name: docker-pgadmin_container
      ports:
        - "5050:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
        PGADMIN_CONFIG_SERVER_MODE: 'False'

    cadvisor:
      image: gcr.io/cadvisor/cadvisor:v0.40.0
      container_name: docker-cadvisor
      privileged: true
      command:
        - '-port=8090'
      ports:
        - "8090:8090"
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro

    prometheus:
      image: prom/prometheus:v2.30.0
      container_name: docker-prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
      image: grafana/grafana:8.1.5
      container_name: docker-grafana
      ports:
        - "3000:3000"
      volumes:
        - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
        - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
        - ./grafana/data/:/var/lib/grafana/dashboards/
      environment:
        - GF_AUTH_BASIC_ENABLED=false
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor