global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'cadvisor'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'cadvisor:8090' ]

  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'app:8080' ]
